version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    build:
      context: .
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
